name: telegram_bot_env
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.2.10
  - certifi=2020.6.20
  - cffi=1.14.4
  - chardet=3.0.4
  - coreapi=2.3.3
  - coreschema=0.0.4
  - cryptography=3.3.1
  - defusedxml=0.6.0
  - dj-database-url=0.5.0
  - drf-yasg=1.20.0
  - gunicorn=20.0.4
  - idna=2.10
  - inflection=0.5.0
  - itypes=1.2.0
  - Jinja2=2.11.2
  - MarkupSafe=1.1.1
  - oauthlib=3.1.0
  - packaging=20.4
  - psycopg2=2.8.6
  - psycopg2-binary=2.8.6
  - pycparser=2.20
  - PyJWT=2.0.0
  - pyparsing=2.4.7
  - python-decouple=3.3
  - python3-openid=3.2.0
  - pytz=2020.1
  - PyYAML=5.3.1
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - ruamel.yaml=0.16.10
  - ruamel.yaml.clib=0.2.0
  - six=1.15.0
  - typing-extensions=3.7.4.3
  - Unidecode=1.1.1
  - uritemplate=3.0.1
  - urllib3=1.25.10
  - whitenoise=5.2.0
  - python-telegram-bot=13.6