name: telegram_bot_env
channels:
  - conda-forge
  - defaults
dependencies:
  - requests
  - python-decouple=3.3
  - python-telegram-bot=13.6
  - future>=0.16.0
  - certifi
  - tornado>=5.1
  - cryptography